/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataController;
/**
 *
 * @author Ireneo III
 */
public class Login extends javax.swing.JFrame {

    private DataController database;
    /**
     * Creates new form Login
     */
    public Login(DataController db) {
        this.database = db;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_Main_Login = new javax.swing.JPanel();
        jlbl_Login = new javax.swing.JLabel();
        jbtn_Login = new javax.swing.JButton();
        jtf_Email = new javax.swing.JTextField();
        jpf_Password = new javax.swing.JPasswordField();
        jlbl_Password = new javax.swing.JLabel();
        jlbl_Email = new javax.swing.JLabel();
        jlbl__Forgot_Password = new javax.swing.JLabel();
        jlbl_Sign_Up = new javax.swing.JLabel();
        Account_Icon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jpnl_Main_Sign_Up = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jpnl_Main_Login.setBackground(new java.awt.Color(35, 50, 90));
        jpnl_Main_Login.setMinimumSize(new java.awt.Dimension(700, 410));
        jpnl_Main_Login.setPreferredSize(new java.awt.Dimension(700, 410));
        jpnl_Main_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_Login.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_Login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbl_Login.setForeground(new java.awt.Color(23, 22, 22));
        jlbl_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Login.setText("Log In");
        jlbl_Login.setToolTipText("");
        jpnl_Main_Login.add(jlbl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 60, -1, -1));

        jbtn_Login.setBackground(new java.awt.Color(226, 149, 90));
        jbtn_Login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_Login.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Login.setText("Log In");
        jbtn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LoginActionPerformed(evt);
            }
        });
        jpnl_Main_Login.add(jbtn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 323, -1, -1));

        jtf_Email.setBackground(new java.awt.Color(0,0,0,1));
        jtf_Email.setForeground(new java.awt.Color(23, 22, 22));
        jtf_Email.setText("Enter your Email");
        jtf_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_EmailFocusLost(evt);
            }
        });
        jtf_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_EmailActionPerformed(evt);
            }
        });
        jpnl_Main_Login.add(jtf_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 150, 120, -1));

        jpf_Password.setForeground(new java.awt.Color(23, 22, 22));
        jpf_Password.setText("Password");
        jpf_Password.setBackground(new java.awt.Color(0,0,0,1));
        jpf_Password.setEchoChar((char) 0);
        jpf_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpf_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpf_PasswordFocusLost(evt);
            }
        });
        jpnl_Main_Login.add(jpf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 216, 120, -1));

        jlbl_Password.setForeground(new java.awt.Color(23, 22, 22));
        jlbl_Password.setText("Password");
        jpnl_Main_Login.add(jlbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 194, -1, -1));

        jlbl_Email.setForeground(new java.awt.Color(23, 22, 22));
        jlbl_Email.setText("Email");
        jpnl_Main_Login.add(jlbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 128, -1, -1));

        jlbl__Forgot_Password.setForeground(new java.awt.Color(23, 22, 22));
        jlbl__Forgot_Password.setText("Forgot Password?");
        jlbl__Forgot_Password.setToolTipText("");
        jpnl_Main_Login.add(jlbl__Forgot_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 256, -1, -1));

        jlbl_Sign_Up.setForeground(new java.awt.Color(23, 22, 22));
        jlbl_Sign_Up.setText("Sign  Up");
        jlbl_Sign_Up.setToolTipText("");
        jpnl_Main_Login.add(jlbl_Sign_Up, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 361, -1, -1));

        Account_Icon.setBackground(new java.awt.Color(23, 22, 22));
        Account_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/AccountBlack.png"))); // NOI18N
        jpnl_Main_Login.add(Account_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 60, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/background2.png"))); // NOI18N
        Background.setText("jLabel2");
        jpnl_Main_Login.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        getContentPane().add(jpnl_Main_Login, "card3");

        javax.swing.GroupLayout jpnl_Main_Sign_UpLayout = new javax.swing.GroupLayout(jpnl_Main_Sign_Up);
        jpnl_Main_Sign_Up.setLayout(jpnl_Main_Sign_UpLayout);
        jpnl_Main_Sign_UpLayout.setHorizontalGroup(
            jpnl_Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jpnl_Main_Sign_UpLayout.setVerticalGroup(
            jpnl_Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jpnl_Main_Sign_Up, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LoginActionPerformed

    }//GEN-LAST:event_jbtn_LoginActionPerformed

    private void jtf_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_EmailFocusGained
        if ("Enter your Email".equals(jtf_Email.getText())) {
            jtf_Email.setText("");
        }
    }//GEN-LAST:event_jtf_EmailFocusGained

    private void jtf_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_EmailFocusLost
        if ("".equals(jtf_Email.getText())) {
            jtf_Email.setText("Enter your Email");
        }
    }//GEN-LAST:event_jtf_EmailFocusLost

    private void jpf_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpf_PasswordFocusGained
        if ("Password".equals(jpf_Password.getText())) {
            jpf_Password.setEchoChar('\u2022');
            jpf_Password.setText("");
        }
    }//GEN-LAST:event_jpf_PasswordFocusGained

    private void jpf_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpf_PasswordFocusLost
        if ("".equals(jpf_Password.getText())) {
            jpf_Password.setEchoChar((char) 0);
            jpf_Password.setText("Password");
        }
    }//GEN-LAST:event_jpf_PasswordFocusLost

    private void jtf_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_EmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_Icon;
    private javax.swing.JLabel Background;
    private javax.swing.JButton jbtn_Login;
    private javax.swing.JLabel jlbl_Email;
    private javax.swing.JLabel jlbl_Login;
    private javax.swing.JLabel jlbl_Password;
    private javax.swing.JLabel jlbl_Sign_Up;
    private javax.swing.JLabel jlbl__Forgot_Password;
    private javax.swing.JPasswordField jpf_Password;
    private javax.swing.JPanel jpnl_Main_Login;
    private javax.swing.JPanel jpnl_Main_Sign_Up;
    private javax.swing.JTextField jtf_Email;
    // End of variables declaration//GEN-END:variables
}
