/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.util.List;
import java.util.Map;
import org.jfree.chart.ChartPanel;
import view.charts.Histogram;
import view.charts.PieChart;

/**
 *
 * @author Ireneo III
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        
//        String[] months = {"Jan", "Feb", "Mar", "Apr"};
//        double[] usage = {120.0, 150.5, 130.0, 160.3};
//
//        Histogram histogramPanel = new Histogram(
//            "Monthly Electricity Usage",
//            "Usage",
//            "kWh",
//            months,
//            usage
//        );
//        jPanel1.setLayout(new BorderLayout());
//        jPanel1.add(histogramPanel, BorderLayout.CENTER);
//        jPanel1.revalidate();
//        jPanel1.repaint();
        

        PieChart pieChart = new PieChart();


        // Optional: set preferred size if needed
        pieChart.setPreferredSize(new java.awt.Dimension(1900, 1080));
        
        

        // Clear existing layout (GroupLayout is default)

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(pieChart, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();

        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
